version: "3.8"
services:
  atlas_db:
    container_name: atlas_db
    image: "lyrasis/blazegraph:2.1.5"
    # Uncomment if you want to access blazegraph interface in your browser (http://localhost:8888)
    ports:
      - "8112:8080"
    volumes:
      - .:/app
      - ./blaze_vm.properties:/RWStore.properties
    restart: always

  atlas_sparqlanything:
    container_name: atlas_sparqlanything
    image: facadex/sparql-anything:latest
    ports:
      #- "8081:3000"
      - "8113:3000"
    restart: always

  atlas:
    container_name: atlas
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - atlas_sparqlanything
      - atlas_db
    volumes:
      - .:/app
      # - static_data:/app/static  # Share static files with nginx
    ports:
      #- "8080:8080"
      - "8114:8080"
    stdin_open: true
    tty: true
    command:
      - "/wait-for-it.sh"
      - "atlas_db:8080"
      - "--"
      - "gunicorn"
      - "--workers=4"
      - "--threads=2"
      - "--bind=0.0.0.0:8080"
      - "app:wsgiapp"
    environment:
      BLAZEGRAPH_ENDPOINT: "http://atlas_db:8080/bigdata/sparql"
      SPARQL_ANYTHING_ENDPOINT: "http://atlas_sparqlanything:3000/sparql.anything"
      PUBLIC_BLAZEGRAPH_ENDPOINT: "http://localhost:8080/sparql"
    restart: unless-stopped
  atlas_nginx:
    container_name: atlas_nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.prod
    volumes:
      - ./static:/app/static
    ports:
      #- 80:80
      - "8115:80"
    depends_on:
      - atlas
    restart: unless-stopped
# volumes:
  # blazegraph_data:
