version: "3.8"
services:
  db:
    container_name: db
    build: 
      context: .
      dockerfile: Dockerfile.blazegraph.prod
    image: dhatlas-db:0.1.0
    # image: "lyrasis/blazegraph:2.1.5"
    # Uncomment if you want to access blazegraph interface in your browser (http://localhost:8888) 
    #  ports:
    #   - 8888:8080
    volumes:
      - blazegraph_data:/app/data
      - blazegraph_records:/app/records
      - blazegraph_vocabs:/app/vocabs
      # - .:/app
    restart: always

  sparqlanything:
    container_name: sparqlanything
    image: facadex/sparql-anything:latest
    ports:
      - "8081:3000"
    restart: always

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: dhatlas-web:0.1.0
    depends_on:
      - sparqlanything 
      - db
    volumes:
      # - .:/app
      - blazegraph_data:/app/data
      - blazegraph_records:/app/records
      - blazegraph_vocabs:/app/vocabs
      - static_data:/app/static  # Share static files with nginx
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command:
      - "/wait-for-it.sh"
      - "db:8080"
      - "--"
      - "gunicorn"
      - "--workers=4"
      - "--threads=2"
      - "--bind=0.0.0.0:8080"
      - "app:wsgiapp"
    environment: 
      BLAZEGRAPH_ENDPOINT: "http://db:8080/bigdata/sparql"
      SPARQL_ANYTHING_ENDPOINT: "http://sparqlanything:3000/sparql.anything"
      PUBLIC_BLAZEGRAPH_ENDPOINT: "http://localhost:8080/sparql"
    restart: unless-stopped

  init-static:
    image: busybox
    volumes:
      - static_data:/app/static
    command: ["/bin/sh", "-c", "cp -r /app/static_default/* /app/static || true"]

  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx.prod
    image: dhatlas-nginx:0.1.0
    volumes:
      - static_data:/app/static
    ports:
      - 80:80
    depends_on:
      - web
    restart: unless-stopped
volumes:
  blazegraph_data:
  blazegraph_records:
  blazegraph_vocabs:
  static_data: